;
;;  ============================================================================================================================================================
;;  Layout Selection Override file
;;  for EPiKaL Portable Keyboard Layout (EPKL) by Øystein "DreymaR" Bech-Aase (2015-), based on PKL by Máté Farkas (2008-2010).
;;  For more info, see the README files and the Big Bag Of Keyboard Tricks: https://dreymar.colemak.org – select Windows.
;
;;  - For Layout choice and settings, use the EPKL_Layouts .ini file(s). For program settings, use EPKL_Settings.
;;  - For each of these, there is a Default file and optionally an Override file, the settings in which take precedence.
;;  - For Extend layer mappings (navigation/editing etc), see the _eD_Extend.ini file. Set the modifier key in any active LayStack file.
;;  - In the Files folder there are Compose, DeadKeys, Extend, PwrStrings and Remap special files with different types of entries.
;;  ============================================================================================================================================================
;
;;  The EPKL Settings GUI:
;;  - You can set the active layout with a handy EPKL Settings window from the EPKL Layout/Settings menu.
;;  - Any changes you submit from that window will be written to your Override (or layout) file, thus taking precedence.
;;  - If you wish, you can then edit the entries manually in the Override file. You may also Reset them with a button.
;;  - The Settings GUI can also change general settings, special keys (Extend and Compose) and individual key mappings.
;
;;  EPKL Layouts Override file info:
;;  - This file takes precedence over EPKL_Layouts_Default.ini if it's present. Rename or delete it to use the Default file only.
;;  - Any setting that's commented out here by prepending its line with a semicolon, will revert to its Default value.
;;  - The first active line under a section such as [pkl] in this file will be used; or failing that, the Default file.
;;  - For more info about the settings below, see the Default file.
;;  - I've added some example settings that are more advanced than the defaults, and closer to what I use myself. Have fun!
;

[pkl]
;layout = Colemak\Cmk-eD\Cmk-eD_ANS_CurlAngleSym:Colemak-eD CurlAngleSym(ANS) 		; Generated by the EPKL LayoutPicker UI, 2025-12-01_15-08
layout = Colemak\Cmk-eD\Cmk-eD_ANS_CurlAngle:Colemak-eD CurlAngle(ANS) 		; Generated by the EPKL LayoutPicker UI, 2025-12-01_15-06
;layout = Colemak\Cmk-eD\Cmk-eD_ANS_CurlAngle:Colemak-DH ANSI Custom

[layout]
QWCLK = ESCAPE/Ext    VKey 		; Generated by the EPKL SpecialKeys UI, 2024-08-03_15-26
;;  ============================================================================================================================================================
